version: "3.9"

services:
  analysis:
    image: cat-movement-analysis
    volumes:
      - ./plots:/app/plots

  tests:
    image: cat-movement-analysis
    entrypoint: pytest
    command: -v

  lint:
    image: cat-movement-analysis
    entrypoint: ruff
    command: check .

  format:
    image: cat-movement-analysis
    entrypoint: ruff
    command: format --check