name: pytest_codecov_wo_token.yml
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Install project (incl. dev dependencies)
        run: uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: |       
          uv run pytest \
            --doctest-modules \
            --cov=src \
            --cov-report=xml \
            tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

      - name: Run ruff linter
        if: always()
        uses: astral-sh/ruff-action@v3

      - name: Run ruff formatter
        if: always()
        run: ruff format --check --diff